version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ConsoleApp/Dockerfile
    volumes:
      - ./chunks:/app/chunks
      - ./input:/app/input
      - ./output:/app/output
      - ./logs:/app/logs
    depends_on:
      - sqlserver
      - elasticsearch
      - kibana
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Sayyar@Passw0rd
      - MSSQL_PID=Express
    volumes:
      - sqlserver_data:/var/opt/mssql
    ports:
      - "1433:1433"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.1
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms256m -Xmx256m"
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.1
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200

volumes:
  sqlserver_data:
  es_data: